### PR TITLE
[DC-18] Initial support for non-English articles

### PR DESCRIPTION
**Pull request by ruyl**
## Summary
Added support for foreign language articles. Using the Microsoft  Translate API, Detects the language of every article which does not already have a language in it's ArticleData's Outlet object, and then based on the detected language or language that was present before detection translates the headline and appends [Translated from <language code>: <translated headline>] to the ArticleData's headline field. Upon error being returned from the language API these functions will not replace the language that was originally detected for the article, and the attempt at translation will return "Translation error" as the translated article headline.
To do this I had to fix a bug in the shared_types file whereby through the lookup function (line 144) the outlet for all articles was inadvertently being set to the **same** singleton empty_obj and causing a mess whenever the outlet for any single ArticleData object was being modified.

## Testing Plan
I have tested this by conducting the typical execution of run.py multiple times with international search terms in the pull_search.py file, both with and without a valid API key present, and it showed expected results in either case.

## Affected Services
Metadata extraction

### CODE REVIEW

**Comment by ruyl** [comment]
[Add support for non-English articles using Microsoft's translation API](https://trello.com/c/E75ZM0q7/39-add-support-for-non-english-articles-using-microsofts-translation-api)

**Comment by caiismyname** [comment]
Looks good! Can you post a comment with a simple example of what the translation outputs, just to see/curiosity?

**Comment by caiismyname** [comment]
(whoops my bad with the closing/reopening). 

Requesting changes just to block this for a bit so we an have sequential merges and not have merge conflicts across everything

**Comment by ruyl** [comment]
This is an example of the kind of articledata class printout this produces:
 {                                                                                                                                                                                                                                           
    "articleId": "",                                                                                                                                                                                                                         
    "authors": [],                                                                                                                                                                                                                           
    "coverageDate": "2018-10-11",                                                                                                                                                                                                            
    "headline": "2019Niche\u7f8e\u56fd\u5927\u5b66\u6392\u540d\u6700\u5168\u6c47\u603b!\u54ea\u6240\u5b66\u6821\u6700\u597d,\u8c01\u6700\u96be\u7533\u8bf7? [Translated from zh-Hans: 2019Niche American University Rankings most complete! which school is best, who is the hardest to apply?]",                                                                                                                                                                                          
    "language": "zh-Hans",                                                                                                                                                                                                                   
    "locale": "unknown",                                                                                                                                                                                                                     
    "mediaOutletName": "unknown",                                                                                                                                                                                                            
    "mediaType": "unknown",                                                                                                                                                                                                                  
    "relatedArticleID": "unknown",                                                                                                                                                                                                           
    "scope": "unknown",                                                                                                                                                                                                                      
    "url": "https://www.zuinow.com/n10103804.html"                                                                                                                                                                                           
}

**Pull request merged**
